name: DeepFilterNet Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-deepfilternet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deepfilternet==0.4.0

      - name: Check if test.wav exists
        run: ls -R data || echo "data/test.wav not found"

      - name: Create Output Directory
        run: mkdir -p output

      - name: Run DeepFilterNet Demo
        run: python -m deepfilternet.demo --no_plot --input data/test.wav --output output/output.wav
