name: DeepFilterNet Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check Python Path
        run: which python

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install deepfilternet==0.4.0  # نصب مستقیم اگر فایل requirements.txt نبود
          fi

      - name: Check Installed Packages
        run: pip list

      - name: Run DeepFilterNet Demo
        run: python -m deepfilternet.demo --no_plot --input data/test.wav --output output.wav
